### ISSUE TITLE
v7.1 Crashes when starting/refreshing mod list.

### ISSUE THREAD

**Issue by ThinkingFingers** [aa2g/AA2Install#19]
Can only start the program with the mods folder empty. 

[AA2Install crash 11-1-2018 06-27-33.zip](https://github.com/aa2g/AA2Install/files/1622352/AA2Install.crash.11-1-2018.06-27-33.zip)

**Comment by ThinkingFingers** [comment]
Cool. I've just been using the previous version. Good luck :)

**Comment by patrickb8man** [comment]
No problem
