### ISSUE TITLE
Fatal Error on launch

### ISSUE THREAD

**Issue by internetakias** [aa2g/AA2Install#2]
Log:
Object reference not set to an instance of an object.
   in AA2Install.CustomListViewSorter.Compare(Object x, Object y) at C:\Program Files (x86)\Jenkins\jobs\AA2Install\workspace\AA2Install\formMain.cs:line 1670
   in System.Windows.Forms.ListView.CompareFunc(IntPtr lparam1, IntPtr lparam2, IntPtr lparamSort)
   in System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   in System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   in System.Windows.Forms.Control.DefWndProc(Message& m)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.ListView.WndProc(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Attachments: 
[config.json.gz](https://github.com/aa2g/AA2Install/files/81394/config.json.gz)
http://b.1339.cf/uxhiirb.dmp

**Comment by patrickb8man** [comment]
That looks like your config.json.gz is partially corrupt / encountered a change in the mods that it couldn't expect. You can try to delete it and the program will regenerate it, but you will lose your preferences (which usually fixes the issue).

**Comment by patrickb8man** [comment]
Assumed fixed.

**Comment by internetakias** [comment]
Yeah, it's fixed
