### ISSUE TITLE
AA2Snowflake 2.0 crash

### ISSUE THREAD

**Issue by cacass** [aa2g/AA2Install#7]
Can't even start the program on Windows Vista 32bit.

[AA2Snowflake crash.zip](https://github.com/aa2g/AA2Install/files/197713/AA2Snowflake.crash.zip)

**Comment by patrickb8man** [comment]
I've moved the issue over [here](https://github.com/aa2g/AA2Snowflake/issues/5), since I've messed up the links in the crash dialog.
